services:
  db:
    image: bitnami/postgresql:latest
    container_name: postgres-brevly
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=brevly
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
      - db:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    restart: unless-stopped
    container_name: brevly-server
    ports:
      - 3333:3333
    environment:
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL

volumes:
  db:
